### ISSUE TITLE
Not working on W10 (This device cannot start. (Code 10)) - The adapter works on Catalina

### ISSUE THREAD

**Issue by jon-torres** [ameeno/DELL-DW1820A-Drivers#6]
Hi,

I have the fenvi/Lenovo's variant of the dw1820 and it's working great on Catalina (hackintosh). I have followed your readme and tried to install the driver on windows with no luck. After the install, that's the message I get.

Thanks.

**Comment by jon-torres** [comment]
I selected the wrong adapter at the device manager, sorry. It's working great, thanks.

**Comment by i3p9** [comment]
@daitro Hey I'm having the same issue. Which adapter did you end up choosing in Device manager? Thanks!
